version: 0.2
phases:
  install:
   runtime-versions:
    nodejs: 18
   commands:
    - cd react-portfolio-template
    - npm ci
  build:
   commands:
    - cd react-portfolio-template
    - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: react-portfolio-template/build
