version: 0.2
phases:
  pre_build:
   commands:
    - echo " Listing repos contents"
    - ls -la
    - echo "current directory is $(pwd)"

  install:
   runtime-versions:
    nodejs: 18
   commands:
    - echo "current directory is $(pwd)"
    - cd react-portfolio-template
    - echo "current directory is $(pwd)"
    - npm ci
  build:
   commands:
    - echo "current directory is $(pwd)"
    - npm run build
    - echo "=== Listing all directories after build ==="
    - ls -la
    - echo "=== Checking if build folder exists ==="
    - ls -la build || echo "No build folder found"
    - echo "=== Checking if dist folder exists ==="
    - ls -la dist || echo "No dist folder found"
artifacts:
  files:
    - '**/*'
  base-directory: react-portfolio-template/build
